### PR TITLE
Improving Python 2 compatibility

### PR DESCRIPTION
**Pull request by inkenbrandt**
`tkinter.font` is strictly a python 3 class; its synonymous python 2 class is `tkFont` (I think).

### CODE REVIEW

**Comment by dmnfarrell** [comment]
Are you using linux or windows to test this. I am not 100% sure all these changes are needed since they should mostly be handled by python-future. Though I did have a problem with simpledialog.
For example import tkinter.font works for me on python 2.7. When I install the package in a virtual environment things also seem to work. 
ie:
https://github.com/PythonCharmers/python-future/blob/master/src/tkinter/font.py

**Comment by inkenbrandt** [comment]
I am getting the same errors on both my linux and windows machines, but maybe my Python 2 is out of date.

Here are the specs on my windows machine:
```
Operating System Windows 7
Python Version 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
Pandas Version 0.17.1
Numpy Version 1.10.4
Matplotlib Version 1.5.1
```

**Comment by dmnfarrell** [comment]
No any version of 2.7 should work. Can you post a couple of the import errors? Perhaps because I am using Ubuntu with both 2 and 3 installed its masking them.

**Comment by inkenbrandt** [comment]
```

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-cb580b341da5> in <module>()
----> 1 import pandastable

c:\python27\arcgis10.3\lib\site-packages\pandastable\__init__.py in <module>()
----> 1 from .core import *
      2 from .data import *
      3 __version__ = '0.7.0'

c:\python27\arcgis10.3\lib\site-packages\pandastable\core.py in <module>()
     20 """
     21 
---> 22 from tkinter import *
     23 from tkinter.ttk import *
     24 from tkinter import filedialog, messagebox, simpledialog

ImportError: No module named tkinter
```

**Comment by inkenbrandt** [comment]
The patch-2 branch hasn't thrown any errors at me yet.

**Comment by dmnfarrell** [comment]
Do you definitely have future and pyttk installed?

**Comment by inkenbrandt** [comment]
That was the problem!  I thought they were base packages.

**Comment by dmnfarrell** [comment]
Ok! I have just pushed a small change and hopefully it will work for you with future installed. If so I can put this version 0.7.1 on pypi. If not let me know.

**Comment by inkenbrandt** [comment]
Yes!  Ver 0.7.1 works with `future` and `pyttk` installed.  Sorry for the bother.

**Comment by dmnfarrell** [comment]
No problem. Thanks for the input.

**Pull request closed without merging**
